create table schema_migrations
(
    version bigint  not null
        primary key,
    dirty   boolean not null
);

alter table schema_migrations
    owner to root;

create table subject
(
    id   bigint generated by default as identity
        primary key,
    name text not null
);

alter table subject
    owner to root;

create table sections
(
    subjectid   integer not null
        constraint sections_subject_id_fk
            references subject
            on delete cascade,
    name        text    not null,
    description text    not null,
    id          bigint generated by default as identity
        primary key
);

alter table sections
    owner to root;

create table formulas
(
    id          uuid not null
        primary key,
    section_id  integer
        constraint formulas_sections_id_fk
            references sections
            on delete cascade,
    name        text not null,
    description text,
    expression  text not null,
    parameters  text[],
    difficulty  smallint,
    video_link  text,
    video_name  text
);

alter table formulas
    owner to root;

create table users
(
    id              uuid                 not null
        primary key,
    telegramid      bigint               not null
        unique,
    username        text                 not null,
    need_onboarding boolean default true not null
);

alter table users
    owner to root;

create table formula_likes
(
    user_id    uuid not null
        constraint formula_likes_user_fk
            references users
            on delete cascade,
    formula_id uuid not null
        constraint formulas_likes_formula_fk
            references formulas
            on delete cascade,
    created_at timestamp default CURRENT_TIMESTAMP,
    primary key (user_id, formula_id)
);

alter table formula_likes
    owner to root;

create table tasks
(
    id         uuid not null
        primary key,
    formula_id uuid
        constraint tasks_formulas_id_fk
            references formulas,
    difficulty integer,
    task_text  text,
    result     double precision
);

alter table tasks
    owner to root;

create table conversations
(
    id        uuid not null
        primary key,
    user_id   uuid
        constraint conversation_user_fk
            references users,
    messages  text[],
    createdat timestamp with time zone default now()
);

alter table conversations
    owner to root;


create table user_stats
(
    id uuid not null,
    user_id uuid
        constraint user_stats_user_fk
            references users,
    "right" int,
    "fail" int,
    completed_at timestamp with time zone
)