create table if not exists sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subjectId   integer not null
        constraint sections_subject_id_fk
            references subject (id)
            on delete cascade,
    name text not null,
    description text not null
);


create table if not exists  subject (
    id bigint generated by default as identity primary key,
    name text not null
);

CREATE TABLE if not exists  formulas
(
    id UUID PRIMARY KEY,
    section_id INTEGER
        CONSTRAINT formulas_sections_id_fk
            REFERENCES sections(id)
            ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    expression TEXT NOT NULL,
    parameters TEXT[],
    difficulty SMALLINT
);

CREATE TABLE if not exists  users
(
    id UUID PRIMARY KEY,
    telegramId BIGINT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    registered_at TIMESTAMP
);

create table if not exists  formula_likes
(
    user_id uuid
        constraint formula_likes_user_fk
            references users(id)
            on delete cascade,
    formula_id uuid
        constraint formulas_likes_formula_fk
            references formulas(id)
            on delete cascade,
    created_at timestamp default current_timestamp,
    primary key (user_id, formula_id)

);

