services:
  postgres:
    container_name: formulink_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main-network
    restart: unless-stopped
    command: [ "postgres", "-c", "listen_addresses=*" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: formulink_redis_container
    image: redis
    volumes:
      - ./storage/redis:/data
    ports:
      - "6379:6379"
    networks:
      - main-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  main-service:
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formulink_server_container
    networks:
      - main-network
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  main-network:
    driver: bridge
    
    